"""Generates hardened Docker configuration files for CrabPot."""

import shutil
from pathlib import Path

from jinja2 import BaseLoader, Environment

from crabpot.paths import CONFIG_DIR, EGRESS_PROXY_PORT

DEFAULT_CPU_LIMIT = "2"
DEFAULT_MEMORY_LIMIT = "2g"
DEFAULT_PIDS_LIMIT = 200


class ConfigGenerator:
    """Generates docker-compose.yml, Dockerfile, seccomp profile, and .env."""

    def __init__(
        self,
        config_dir: Path = CONFIG_DIR,
        cpu_limit: str = DEFAULT_CPU_LIMIT,
        memory_limit: str = DEFAULT_MEMORY_LIMIT,
        pids_limit: int = DEFAULT_PIDS_LIMIT,
    ):
        self.config_dir = config_dir
        self.cpu_limit = cpu_limit
        self.memory_limit = memory_limit
        self.pids_limit = pids_limit
        self.jinja_env = Environment(loader=BaseLoader(), keep_trailing_newline=True)

    def generate_all(self) -> None:
        """Generate all configuration files to the config directory."""
        self.config_dir.mkdir(parents=True, exist_ok=True)
        self._generate_seccomp_profile()
        self._generate_dockerfile()
        self._generate_compose()
        self._generate_env_file()
        self._generate_egress_allowlist()

    def _read_template(self, name: str) -> str:
        """Read a template from the package's templates directory."""
        templates_dir = Path(__file__).parent / "templates"
        return (templates_dir / name).read_text()

    def _generate_seccomp_profile(self) -> None:
        """Copy the seccomp profile to the config directory."""
        src = Path(__file__).parent / "templates" / "seccomp-profile.json"
        dst = self.config_dir / "seccomp-profile.json"
        shutil.copy2(src, dst)

    def _generate_dockerfile(self) -> None:
        """Render and write the hardened Dockerfile."""
        template_str = self._read_template("Dockerfile.j2")
        template = self.jinja_env.from_string(template_str)
        rendered = template.render()
        (self.config_dir / "Dockerfile.crabpot").write_text(rendered)

    def _generate_compose(self) -> None:
        """Render and write the docker-compose.yml with security settings."""
        template_str = self._read_template("docker-compose.yml.j2")
        template = self.jinja_env.from_string(template_str)

        seccomp_path = str(self.config_dir / "seccomp-profile.json")

        rendered = template.render(
            seccomp_path=seccomp_path,
            cpu_limit=self.cpu_limit,
            memory_limit=self.memory_limit,
            pids_limit=self.pids_limit,
            egress_proxy_port=EGRESS_PROXY_PORT,
        )
        (self.config_dir / "docker-compose.yml").write_text(rendered)

    def _generate_egress_allowlist(self) -> None:
        """Copy the default egress allowlist to the config directory."""
        dest = self.config_dir / "egress-allowlist.txt"
        if dest.exists():
            return  # Don't overwrite user-customized policy
        src = Path(__file__).parent / "templates" / "egress-allowlist.txt"
        shutil.copy2(src, dest)

    def _generate_env_file(self) -> None:
        """Generate a default .env file for OpenClaw configuration."""
        env_path = self.config_dir / ".env"
        if env_path.exists():
            return  # Don't overwrite existing config

        env_content = (
            "# OpenClaw Configuration\n"
            "# Generated by CrabPot — edit as needed\n"
            "\n"
            "# Gateway port (inside container)\n"
            "PORT=18789\n"
            "\n"
            "# Add your API keys and config below:\n"
            "# OPENAI_API_KEY=\n"
            "# ANTHROPIC_API_KEY=\n"
        )
        env_path.write_text(env_content)

    def get_config_summary(self) -> dict:
        """Return a summary of the current configuration."""
        return {
            "config_dir": str(self.config_dir),
            "cpu_limit": self.cpu_limit,
            "memory_limit": self.memory_limit,
            "pids_limit": self.pids_limit,
            "files": [f.name for f in self.config_dir.iterdir()] if self.config_dir.exists() else [],
        }
